# Generated by cucumber-sinatra. (2014-05-15 17:26:14 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/patas.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Patas

class PatasWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  PatasWorld.new
end
